# Docker environment settings that override the defaults
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

# Add Kafka configuration
spring.kafka.bootstrap-servers=broker:29092
spring.kafka.consumer.bootstrap-servers=broker:29092
spring.kafka.producer.bootstrap-servers=broker:29092
spring.kafka.consumer.group-id=notes-group
app.kafka.notes-topic=note-content-topic
spring.kafka.properties.auto.create.topics.enable=true