spring.application.name=fileHandlingService
server.port=8082

spring.profiles.active=dev

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.notes-topic=notes-content-topic
spring.kafka.properties.auto.create.topics.enable=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Kafka Logging
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=WARN

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:5050/realms/notes-application
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:5050/realms/notes-application/protocol/openid-connect/certs