services:

  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_USER=myuser'
      - 'RABBITMQ_DEFAULT_PASS=secret'
    ports:
      - '5672:5672'
      - '15672:15672'

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  redis:
    image: redis/redis-stack:latest
    container_name: redis_dockerfile
    ports:
      - '6379:6379'
      - '8001:8001'
    command: [ "/entrypoint.sh", "./redis-stack.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  discovery-server:
    build: ./discoveryServer
    container_name: discovery-server
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  api-gateway:
    build: ./apiGateway
    container_name: api-gateway
    ports:
      - '8181:8181'
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=apiGateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  notes-application:
    build: ./
    container_name: notes
    hostname: notes-application
    ports:
      - '8080:8080'
    depends_on:
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: [ "java", "-Dspring.profiles.active=docker", "-jar", "/app/notes-application.jar" ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=NotesApplication
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    volumes:
      - /tmp/jasper-reports:/tmp

  file-service:
    build: ./fileHandlingService
    container_name: file-service
    ports:
      - '8082:8082'
    depends_on:
      discovery-server:
        condition: service_healthy
      broker:
        condition: service_started
    environment:
      - SPRING_APPLICATION_NAME=fileHandlingService
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092

  notification-service:
    build: ./NotificationService
    container_name: notification-service
    ports:
      - '8081:8081'
    depends_on:
      discovery-server:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - SPRING_APPLICATION_NAME=NotificationService
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=myuser
      - SPRING_RABBITMQ_PASSWORD=secret

volumes:
  redis_data:
    driver: local