spring.application.name=NotesApplication


# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:5050/realms/notes-application
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:5050/realms/notes-application/protocol/openid-connect/certs

# Ensure logging is enabled for debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.note.notesapplication.Util=DEBUG
server.error.include-stacktrace=always
server.error.include-message=always

spring.docker.compose.enabled=false
eureka.instance.hostname=localhost
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.preferIpAddress=false
eureka.instance.appname=NotesApplication
eureka.instance.instanceId=${spring.application.name}:${server.port}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none

# Kafka settings
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notes-group
app.kafka.notes-topic=note-content-topic
spring.kafka.properties.auto.create.topics.enable=true

app.kafka.user-registration-topic=user-registration-topic

# Logging for MongoDB driver
logging.level.org.springframework.data.mongodb.core=DEBUG

# Kafka Logging
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=WARN