spring.application.name=apiGateway
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.main.web-application-type=reactive
server.port=8181

#Keycloak Configuration
keycloak.auth-server-url=http://localhost:5050
keycloak.realm=notes-application
keycloak.resource=notes-app
keycloak.credentials.secret=uQ9RetQ4A0EJuf7OZuG20twGISRsw7Yx

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:5050/realms/notes-application
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:5050/realms/notes-application/protocol/openid-connect/certs


# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.user-registration-topic=user-registration-topic

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

spring.cloud.gateway.routes[0].id=notes-service
spring.cloud.gateway.routes[0].uri=lb://NotesApplication
spring.cloud.gateway.routes[0].predicates[0]=Path=/notesApplication/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=CircuitBreaker=notesApplication,forward:/fallback/notesApplication
spring.cloud.gateway.routes[0].metadata.connect-timeout=60000
spring.cloud.gateway.routes[0].metadata.response-timeout=60000

spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://NotificationService
spring.cloud.gateway.routes[1].predicates[0]=Path=/notificationService/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=CircuitBreaker=notificationService,forward:/fallback/email
spring.cloud.gateway.routes[1].metadata.connect-timeout=60000
spring.cloud.gateway.routes[1].metadata.response-timeout=60000

spring.cloud.gateway.routes[2].id=file-handling-service
spring.cloud.gateway.routes[2].uri=lb://fileHandlingService
spring.cloud.gateway.routes[2].predicates[0]=Path=/fileHandling/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[2].filters[1]=CircuitBreaker=fileHandling,forward:/fallback/fileHandling

# Increase timeouts for the file handling route
spring.cloud.gateway.routes[2].metadata.connect-timeout=60000
spring.cloud.gateway.routes[2].metadata.response-timeout=60000

# Add a specific route for reports with higher timeouts
spring.cloud.gateway.routes[3].id=notes-reports
spring.cloud.gateway.routes[3].uri=lb://NotesApplication
spring.cloud.gateway.routes[3].predicates[0]=Path=/notesApplication/users/*/reports/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[3].filters[1]=CircuitBreaker=notesReports,forward:/fallback/notesApplication
spring.cloud.gateway.routes[3].metadata.connect-timeout=120000
spring.cloud.gateway.routes[3].metadata.response-timeout=120000

# Add this to your application.properties file
spring.cloud.gateway.routes[4].id=auth-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[4].uri=forward:/

# Add circuit breaker config for reports
resilience4j.circuitbreaker.instances.notesReports.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notesReports.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notesReports.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.notesReports.waitDurationInOpenState=500000
resilience4j.circuitbreaker.instances.notesReports.failureRateThreshold=50
resilience4j.timelimiter.instances.notesReports.timeoutDuration=150s

# Resilience4j circuit breaker configuration
resilience4j.circuitbreaker.instances.notesApplication.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notesApplication.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notesApplication.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.notesApplication.waitDurationInOpenState=500000
resilience4j.circuitbreaker.instances.notesApplication.failureRateThreshold=50
resilience4j.timelimiter.instances.notesApplication.timeoutDuration=150s

resilience4j.circuitbreaker.instances.notificationService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notificationService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notificationService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.notificationService.waitDurationInOpenState=50000
resilience4j.circuitbreaker.instances.notificationService.failureRateThreshold=50
resilience4j.timelimiter.instances.notificationService.timeoutDuration=150s

resilience4j.circuitbreaker.instances.fileHandling.slidingWindowSize=10
resilience4j.circuitbreaker.instances.fileHandling.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.fileHandling.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.fileHandling.waitDurationInOpenState=50000
resilience4j.circuitbreaker.instances.fileHandling.failureRateThreshold=50
resilience4j.timelimiter.instances.fileHandling.timeoutDuration=150s

spring.cloud.loadbalancer.retry.enabled=true
spring.cloud.loadbalancer.retry.max-retries-on-same-service-instance=1
spring.cloud.loadbalancer.retry.max-retries-on-next-service-instance=2