spring.application.name=NotificationService
server.port=8081

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.sendgrid.api-key=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
sendgrid.from.email=manish.moryani@hashstudioz.com

twilio.account.sid=AC32563a7ca2487f847152170f377da876
twilio.auth.token=0163fb181d076b6988f4398c303d9a5a